### ISSUE TITLE
Entity parameter expansion fails when resolving from a catalog

### ISSUE THREAD

**Issue by ChrisTrenkamp** [FasterXML/woodstox#100]
Test.java
```java
import com.ctc.wstx.stax.WstxInputFactory;
import com.ctc.wstx.stax.WstxOutputFactory;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLResolver;
import javax.xml.stream.XMLStreamException;
import org.apache.commons.configuration2.resolver.CatalogResolver;
import org.xml.sax.SAXException;

public class Test {
  public static void main(String[] args) {
    try {
      var xmlInputFactory = new WstxInputFactory();
      var resolver = new CatalogResolver();
      resolver.setCatalogFiles("catalog.xml");
      var xmlResolver =
          (XMLResolver)
              (publicID, systemID, baseURI, namespace) -> {
                try {
                  return resolver.resolveEntity(publicID, systemID).getByteStream();
                } catch (SAXException e) {
                  throw new RuntimeException(e);
                }
              };
      xmlInputFactory.setProperty(XMLInputFactory.RESOLVER, xmlResolver);
      var xml = xmlInputFactory.createXMLEventReader(new File("test.xml"));
      var buffer = new ByteArrayOutputStream();
      var out = new WstxOutputFactory().createXMLEventWriter(buffer);
      while (xml.hasNextEvent()) {
        out.add(xml.nextEvent());
      }
      System.out.println(buffer.toString());
    } catch (XMLStreamException e) {
      throw new RuntimeException(e);
    }
  }
}
```

catalog.xml
```
<?xml version="1.0" encoding="utf-8"?>

<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
	<public publicId="-//FOO//BAR//EN" uri="test.dtd"/>
</catalog>
```

test.dtd
```
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % test2 SYSTEM "test2.dtd">
%test2;

<!ELEMENT root (#PCDATA)>
```

test2.dtd
```
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY foo "bar">
```

test.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root PUBLIC "-//FOO//BAR//EN" "test.dtd">

<root>&foo;</root>
```

result:
```
Exception in thread "main" java.lang.NullPointerException
	at Test.lambda$0(Test.java:22)
	at com.ctc.wstx.io.DefaultInputResolver.resolveEntity(DefaultInputResolver.java:79)
	at com.ctc.wstx.ent.ParsedExtEntity.expand(ParsedExtEntity.java:77)
	at com.ctc.wstx.sr.StreamScanner.expandEntity(StreamScanner.java:1681)
	at com.ctc.wstx.sr.StreamScanner.expandEntity(StreamScanner.java:1629)
	at com.ctc.wstx.dtd.FullDTDReader.expandPE(FullDTDReader.java:1136)
	at com.ctc.wstx.dtd.FullDTDReader.parseDTD(FullDTDReader.java:566)
	at com.ctc.wstx.dtd.FullDTDReader.readExternalSubset(FullDTDReader.java:447)
	at com.ctc.wstx.sr.ValidatingStreamReader.findDtdExtSubset(ValidatingStreamReader.java:469)
	at com.ctc.wstx.sr.ValidatingStreamReader.finishDTD(ValidatingStreamReader.java:326)
	at com.ctc.wstx.sr.BasicStreamReader.finishToken(BasicStreamReader.java:3821)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2161)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1175)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
	at Test.main(Test.java:32)
```

For some reason, using a catalog in this case causes the entity expansion in test.dtd to fail.  If you directly reference test.dtd from test.xml and not use a catalog, it works fine.  It'll also work if you put the entity in test.dtd and use the catalog.  But for some reason, expanding entity parameters in an external dtd file while using a catalog doesn't work.

**Comment by ChrisTrenkamp** [comment]
Actually, I think this user error.

**Comment by cowtowncoder** [comment]
Ok glad you figured it out.
