### ISSUE TITLE
Strange I/O stream, returned 0 bytes on read

### ISSUE THREAD

**Issue by jbescos** [FasterXML/woodstox#143]
Hello.

Parsing the response of a webservice in Weblogic, there is the next error when the response does not contain XML at all.

```
HTTP/1.1 200 OK
Date: Wed, 06 Apr 2022 06:41:05 GMT
Content-Type: text/xml; charset=utf-8
Content-Length: 0
Connection: keep-alive
```

```
Caused by: javax.xml.soap.SOAPException: Error parsing envelope: most likely due to an invalid SOAP message.: Strange I/O stream, returned 0 bytes on read
	at oracle.j2ee.ws.saaj.soap.AbstractSOAPImplementation.createEnvelope(AbstractSOAPImplementation.java:149)
	at oracle.j2ee.ws.saaj.soap.SOAPPartImpl.getEnvelope(SOAPPartImpl.java:101)
	at oracle.j2ee.ws.saaj.soap.SOAPPartImpl.getEnvelope(SOAPPartImpl.java:65)
	at oracle.j2ee.ws.saaj.soap.MessageImpl.getSOAPBody(MessageImpl.java:1894)
	at oracle.j2ee.ws.common.async.MessageSender.processResponse(MessageSender.java:86)
	at oracle.j2ee.ws.common.async.MessageSender.call(MessageSender.java:72)
	at oracle.j2ee.ws.common.async.Transmitter.transmitSync(Transmitter.java:105)
	at oracle.j2ee.ws.common.async.Transmitter.transmit(Transmitter.java:60)
	at oracle.j2ee.ws.common.async.RequestorImpl.transmit(RequestorImpl.java:256)
	at oracle.j2ee.ws.common.async.RequestorImpl.invoke(RequestorImpl.java:91)
	at oracle.j2ee.ws.client.jaxws.DispatchImpl.invoke(DispatchImpl.java:1388)
	... 164 more
Caused by: com.ctc.wstx.exc.WstxIOException: Strange I/O stream, returned 0 bytes on read
	at com.ctc.wstx.stax.WstxInputFactory.doCreateSR(WstxInputFactory.java:578)
	at com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:633)
	at com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:657)
	at com.ctc.wstx.stax.WstxInputFactory.createXMLStreamReader(WstxInputFactory.java:342)
	at oracle.j2ee.ws.saaj.soap.AbstractSOAPImplementation.getStaXParsedEnvelope(AbstractSOAPImplementation.java:200)
	at oracle.j2ee.ws.saaj.soap.AbstractSOAPImplementation.createEnvelope(AbstractSOAPImplementation.java:70)
	... 174 more
Caused by: java.io.IOException: Strange I/O stream, returned 0 bytes on read
	at com.ctc.wstx.io.BaseReader.reportStrangeStream(BaseReader.java:216)
	at com.ctc.wstx.io.UTF8Reader.loadMore(UTF8Reader.java:376)
	at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:112)
	at com.ctc.wstx.io.ReaderBootstrapper.initialLoad(ReaderBootstrapper.java:254)
	at com.ctc.wstx.io.ReaderBootstrapper.bootstrapInput(ReaderBootstrapper.java:134)
	at com.ctc.wstx.stax.WstxInputFactory.doCreateSR(WstxInputFactory.java:573)

```
```
Bundle-SymbolicName: com.fasterxml.woodstox.woodstox-core
Bundle-Vendor: FasterXML
Bundle-Version: 6.2.6
```

Could com.ctc.wstx.io.UTF8Reader.loadMore return false instead of throwing an exception?

Possible fix: https://github.com/FasterXML/woodstox/pull/144

**Comment by cowtowncoder** [comment]
No, streams must not return `0` as this could easily lead to deadlock (infinite loop) unless caller does something other than try again. 
If there is no more content to read it should return `-1`.

Having said that, if you wanted to add a (Woodstox-)configuration option (false by default) for allowing this behavior, that'd be fine. So by default behavior is like now, but by enabling the feature it could take path that PR does -- basically considering `0` same as `-1`.

The reason I prefer opt-in is that users would be aware of broken stream implementations; and only opt-in to accept faulty responses for interoperability reasons.

**Comment by jbescos** [comment]
Thank you @cowtowncoder I think I can close this because I had more information related to the issue.

That was a response that is supposed to happen in `oracle.j2ee.ws.client.jaxws.DispatchImpl.invokeOneWay` Webservices, so only HTTP status must be check (no XML parse is needed because the response comes in a callback). It looks there is some bug and now the workflow is going through `oracle.j2ee.ws.client.jaxws.DispatchImpl.invoke`, and this requires to parse the response.
