### ISSUE TITLE
Text content is not validated correctly when copying events to `XmlStreamWriter`

### ISSUE THREAD

**Issue by hxc9** [FasterXML/woodstox#23]
Hello,

I found a bug in the way validation is performed for text content when writing to an XmlStreamWriter, which leads to validation errors.

I've tested it with the 5.0.3 release.
Here is the code to reproduce:

```
import com.ctc.wstx.stax.WstxInputFactory;
import com.ctc.wstx.stax.WstxOutputFactory;
import org.codehaus.stax2.XMLStreamReader2;
import org.codehaus.stax2.XMLStreamWriter2;
import org.codehaus.stax2.validation.XMLValidationSchema;
import org.codehaus.stax2.validation.XMLValidationSchemaFactory;

import javax.xml.stream.XMLStreamException;
import java.io.InputStream;
import java.io.StringWriter;

public class Converter {

    public static void main(String... args) throws XMLStreamException {

        InputStream reader = Converter.class.getClassLoader().getResourceAsStream("test.xml");
        StringWriter writer = new StringWriter();

        XMLValidationSchema schema = XMLValidationSchemaFactory.newInstance(XMLValidationSchema.SCHEMA_ID_W3C_SCHEMA)
                .createSchema(Converter.class.getClassLoader().getResourceAsStream("schema.xsd"));


        XMLStreamReader2 xmlReader = (XMLStreamReader2) new WstxInputFactory().createXMLStreamReader(reader);
        xmlReader.validateAgainst(schema);

        XMLStreamWriter2 xmlWriter = (XMLStreamWriter2) new WstxOutputFactory().createXMLStreamWriter(writer);
        xmlWriter.validateAgainst(schema);

        xmlWriter.copyEventFromReader(xmlReader, false);

        while (xmlReader.hasNext()) {
            xmlReader.next();

            xmlWriter.copyEventFromReader(xmlReader, true);
        }

        System.out.println(writer.toString());
    }
}
```

Here is the XML:

```
<?xml version='1.0' encoding='UTF-8'?>
<Document>1</Document>

```

and the schema

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Document" type="xs:int"/>
</xs:schema>
```

Running the example code with those two files results in the following exception being thrown:

```
Exception in thread "main" com.ctc.wstx.exc.WstxValidationException: Unknown reason
 at [row,col {unknown-source}]: [1,61]
    at com.ctc.wstx.exc.WstxValidationException.create(WstxValidationException.java:50)
    at com.ctc.wstx.sw.BaseStreamWriter.reportProblem(BaseStreamWriter.java:1243)
    at com.ctc.wstx.msv.GenericMsvValidator.reportError(GenericMsvValidator.java:549)
    at com.ctc.wstx.msv.GenericMsvValidator.reportError(GenericMsvValidator.java:541)
    at com.ctc.wstx.msv.GenericMsvValidator.reportError(GenericMsvValidator.java:535)
    at com.ctc.wstx.msv.GenericMsvValidator.validateElementEnd(GenericMsvValidator.java:390)
    at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteEndTag(BaseNsStreamWriter.java:742)
    at com.ctc.wstx.sw.BaseNsStreamWriter.writeEndElement(BaseNsStreamWriter.java:291)
    at com.ctc.wstx.sw.BaseStreamWriter.copyEventFromReader(BaseStreamWriter.java:795)
    at Converter.main(Converter.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

When reading that XML, no error occur, this only happens when writing.
Additionnaly, if I change the type of the Document element to xs:string in the XSD, validation is successful.

I've dug a bit into this, my understanding is that the stream writer doesn't pass text content to the validator, GenericMsvValidator#validateText is never called, and as a result GenericMsvValidator#mTextAccumulator stays empty until validateElementEnd is called.

**Comment by cowtowncoder** [comment]
I wonder if this could be related to #16 which was fixed for 5.0.3.

**Comment by hxc9** [comment]
It could be indeed the same kind of error (not passing the text content, respectively for #16 the attributes to the validator).

**Comment by cowtowncoder** [comment]
Turns out calls to validator were being optimized away accidentally by `copyEventFromReader()`, which used direct writes to target writer/stream, instead of delegating to regular `writeXxx()` methods of `XMLStreamWriter` (which call validator callbacks).
