### ISSUE TITLE
Control characters in node is not handled

### ISSUE THREAD

**Issue by samrajcse** [FasterXML/woodstox#71]
I am using Woodstox -5.2.0 for parsing XML response. I am facing few issues with control characters. On research I found the suggestion to add following line.
wstxFactory.setProperty(WstxInputProperties.P_ALLOW_XML11_ESCAPED_CHARS_IN_XML10, true);

Still I am getting the below error. I guess, that was handled for contents and not for xml nodes.

Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Illegal character ((CTRL-CHAR, code 2))
 at [row,col {unknown-source}]: [4,519838]
	at com.ctc.wstx.sr.StreamScanner.throwInvalidSpace(StreamScanner.java:689) ~[woodstox-core-5.2.0.jar:5.2.0]
	at com.ctc.wstx.sr.BasicStreamReader.readTextPrimary(BasicStreamReader.java:4645) ~[woodstox-core-5.2.0.jar:5.2.0]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2951) ~[woodstox-core-5.2.0.jar:5.2.0]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1122) ~[woodstox-core-5.2.0.jar:5.2.0]

**Comment by cowtowncoder** [comment]
That is working as expected: XML content MUST NOT contain unescaped control characters (and in XML 1.0, by default, not even escaped ones). There is no option to ignore that fundamental failure of content.

So whatever is producing response is not creating XML, but something that looks like it and should be fixed.

However, if it is somehow not possible to require actual XML response (and as I said, this is not legal according XML specifications), you may want to write (or use) `InputStream` or `Reader` that filters out such characters, or converts them to spaces, and then pass that to `XMLInputFactory`.

**Comment by samrajcse** [comment]
Is it possible to guide me to remove control characters from xml stream? I tried lot of scenario and still i can't able to achieve. Control character's are not only available in text, in few scenario, it is available in xml tags or in structure.
