### ISSUE TITLE
Get StackOverflow when I specify maxOccurs= "25000"

### ISSUE THREAD

**Issue by vladimirovichsa** [FasterXML/woodstox#87]
Hi, faced such problem when I specify at an element maxOccurs= "25000", I receive an error with StackOverflow.

But if I specify maxOccurs= "unbounded", validation passes and I get my xml even in 100,000 elements which is marked maxOccurs="unbounded".

Stack trace:
`Exception in thread "main" java.lang.StackOverflowError
at java.util.HashMap.putVal(HashMap.java:657)
at java.util.HashMap.put(HashMap.java:612)
at java.util.HashSet.add(HashSet.java:220)
at com.ctc.wstx.shaded.msv_core.reader.xmlschema.AttributeWildcardComputer.onRef(AttributeWildcardComputer.java:131)
at com.ctc.wstx.shaded.msv_core.grammar.ReferenceExp.visit(ReferenceExp.java:109)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onBinExp(ExpressionWalker.java:95)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onSequence(ExpressionWalker.java:91)
at com.ctc.wstx.shaded.msv_core.grammar.SequenceExp.visit(SequenceExp.java:46)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onBinExp(ExpressionWalker.java:95)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onChoice(ExpressionWalker.java:87)
at com.ctc.wstx.shaded.msv_core.grammar.ChoiceExp.visit(ChoiceExp.java:48)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onBinExp(ExpressionWalker.java:96)
at com.ctc.wstx.shaded.msv_core.grammar.util.ExpressionWalker.onSequence(ExpressionWalker.java:91)`

**Comment by cowtowncoder** [comment]
Please include a (unit) test to reproduce the problem. Textual explanation and exception is unfortunately not enough to have an idea of what might be happening.

**Comment by cowtowncoder** [comment]
Also: this may well be a limitation of Multi-Schema Validator (component Woodstox uses for validation modes other than DTD), so if there's a test, probably would need to file an issue against that.

**Comment by vladimirovichsa** [comment]
Good afternoon. Sorry for taking so long to answer. Sample code with xml and xsd posted 
[here ](https://github.com/vladimirovichsa/xml-validate)
